FROM python:3.12-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    gcc \
    libpq-dev \
    && apt-get clean \
    && apt-get install -y iputils-ping \
    && rm -rf /var/lib/apt/lists/*
    
COPY requirements.scheduler.txt .
RUN pip install --no-cache-dir -r requirements.scheduler.txt

COPY . .

CMD ["python", "schedule_run.py"]
